services:
  - type: web
    name: unico-checklist
    runtime: node
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: ADMIN_USER
        value: Creverson
      - key: ADMIN_PASSWORD
        sync: false
      - key: APP_USER
        value: Anderson
      - key: APP_PASSWORD
        sync: false
      - key: DATABASE_URL
        sync: false
      - key: CLOUDINARY_CLOUD_NAME
        sync: false
      - key: CLOUDINARY_API_KEY
        sync: false
      - key: CLOUDINARY_API_SECRET
        sync: false
      - key: CLOUDINARY_FOLDER
        value: unico-checklist
